import { useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import "./App.css";

function App() {
  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const uploadResume = async () => {
    if (!file) {
      alert("Please select a resume");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);

    try {
      setLoading(true);

      const response = await axios.post(
        "https://prepai-backend-7hr4.onrender.com/upload-resume/",
        formData,
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );

      setResult(response.data);
    } catch (error) {
      console.log(error);
      alert("Backend connection failed");
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!result) return;

    const doc = new jsPDF();

    doc.setFont("helvetica", "bold");
    doc.text("PrepAI Resume Report", 20, 20);

    doc.setFont("helvetica", "normal");

    doc.text(`Name: ${result?.candidate_name || ""}`, 20, 40);
    doc.text(`Resume Score: ${result?.score?.resume_score || 0}/100`, 20, 50);
    doc.text(`ATS Score: ${result?.ats_score?.ATS_score || 0}/100`, 20, 60);
    doc.text(`Skills: ${result?.skills?.length || 0}`, 20, 70);
    doc.text(`Projects: ${result?.projects?.length || 0}`, 20, 80);

    doc.text("Generated by PrepAI AI System", 20, 100);

    doc.save("PrepAI_Report.pdf");
  };

  return (
    <div className="container">
      <h1>🚀 PrepAI Resume Analyzer</h1>
      <p>AI-powered resume analysis for placements</p>

      {!result && (
        <>
          <input
            type="file"
            accept=".pdf"
            onChange={(e) => setFile(e.target.files[0])}
          />

          <br />

          <button onClick={uploadResume}>
            {loading ? "Analyzing..." : "Analyze Resume"}
          </button>
        </>
      )}

      {result && (
        <div className="dashboard">

          <div className="dashboard-grid">
            <div className="card blue">
              <h3>📊 Resume Score</h3>
              <h1>{result?.score?.resume_score}/100</h1>
            </div>

            <div className="card green">
              <h3>🎯 ATS Score</h3>
              <h1>{result?.ats_score?.ATS_score}/100</h1>
            </div>

            <div className="card purple">
              <h3>💻 Skills</h3>
              <h1>{result?.skills?.length}</h1>
            </div>

            <div className="card orange">
              <h3>📂 Projects</h3>
              <h1>{result?.projects?.length}</h1>
            </div>
          </div>

          <button onClick={downloadPDF}>
            📄 Download PDF Report
          </button>

          <hr />

          <h2>👤 {result?.candidate_name}</h2>

          <h3>📞 Contact</h3>
          <p><strong>Email:</strong> {result?.contact_info?.email}</p>
          <p><strong>Phone:</strong> {result?.contact_info?.phone}</p>
          <p><strong>LinkedIn:</strong> {result?.contact_info?.linkedin}</p>
          <p><strong>GitHub:</strong> {result?.contact_info?.github}</p>

          <hr />

          <h3>💻 Skills</h3>
          <div>
            {result?.skills?.map((skill, index) => (
              <span className="tag" key={index}>
                {skill}
              </span>
            ))}
          </div>

          <hr />

          <h3>📂 Projects</h3>
          <ul>
            {result?.projects?.map((project, index) => (
              <li key={index}>{project}</li>
            ))}
          </ul>

          <hr />

          <h3>🎓 Education</h3>
          <ul>
            {result?.education?.map((edu, index) => (
              <li key={index}>{edu}</li>
            ))}
          </ul>

          <hr />

          <h3>🤖 AI Feedback</h3>
          <ul>
            {result?.ai_feedback?.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>

          <hr />

          <h3>🎯 ATS Breakdown</h3>

          <p>Keyword Match</p>
          <div className="progress-bar">
            <div
              className="progress-fill"
              style={{ width: `${result?.ats_score?.details?.keyword_match || 0}%` }}
            />
          </div>

          <p>Education Score</p>
          <div className="progress-bar">
            <div
              className="progress-fill"
              style={{ width: `${result?.ats_score?.details?.education_score || 0}%` }}
            />
          </div>

          <p>Project Score</p>
          <div className="progress-bar">
            <div
              className="progress-fill"
              style={{ width: `${result?.ats_score?.details?.project_score || 0}%` }}
            />
          </div>

          <p>Experience Score</p>
          <div className="progress-bar">
            <div
              className="progress-fill"
              style={{ width: `${result?.ats_score?.details?.experience_score || 0}%` }}
            />
          </div>

        </div>
      )}
    </div>
  );
}

export default App;